# Generated by Django 4.0 on 2022-01-07 07:23

import LITReview.utils
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=150, validators=[django.contrib.auth.validators.ASCIIUsernameValidator], verbose_name='Nom')),
                ('last_name', models.CharField(max_length=150, validators=[django.contrib.auth.validators.ASCIIUsernameValidator], verbose_name='Prenom')),
                ('nick_name', models.CharField(blank=True, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name="Nom d'utilisateur (Public)")),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='Date de naissance')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], null=True)),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Adresse')),
                ('zip_code', models.CharField(blank=True, max_length=15, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='Ville')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('profile_picture', models.ImageField(default='no_profile_picture.png', upload_to=LITReview.utils.rename_picture)),
                ('social_1', models.CharField(blank=True, max_length=150, validators=[django.contrib.auth.validators.ASCIIUsernameValidator], verbose_name='Réseau Social #1')),
                ('social_2', models.CharField(blank=True, max_length=150, validators=[django.contrib.auth.validators.ASCIIUsernameValidator], verbose_name='Réseau Social #2')),
                ('social_3', models.CharField(blank=True, max_length=150, validators=[django.contrib.auth.validators.ASCIIUsernameValidator], verbose_name='Réseau Social #3')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
    ]
